version: '3.1'

services:
  redis:
    image: redis:5-alpine
    restart: always
    ports:
      - 127.0.0.1:6379:6379
    # api is the container name for our Go API
  websocket-server:
      # It will look for a dockerfile in the project root and build it
    build: "."
      # Exposes the port 5000 from a container and binds it to a random port
    ports:
      - "8080:8080"
      # If the container goes down, it will restart
    restart: "always"
    
networks: 
  websocket-server.network: